### ISSUE TITLE
Error loading model: value 'AND' is not legal

### ISSUE THREAD

**Issue by agarciadom** [bluezio/ttc2020-ocl2sql#6]
The reference and Epsilon solutions use a statically-generated metamodel which still uses the "and" casing for the operator. Unfortunately, commit b4d4df changed the casing to "AND", and broke both the reference and the Epsilon solution.

Can we either:

* Regenerate the metamodel and upload a new Maven artefact for it (@npbhoang), or
* Revert the change in b4d4df (@georghinkel)?

**Comment by npbhoang** [comment]
Hi @bluezio ,

Yes, I noticed the problem with the "AND".

I believe reverting the change in b4d4df would be the easiest solution.
Also, I don't think this revert will affect the NMF solution of @georghinkel .

**Comment by npbhoang** [comment]
I reverted the change in b4d4df.
@georghinkel , I hope it is okay.

I will run all the solutions again to make sure all works fine.

**Comment by georghinkel** [comment]
I have to investigate why, but NMF currently silently ignores parsing errors and if the casing is not correct, treats the element as equals. That does not make a difference in the scenarios considered.

**Comment by npbhoang** [comment]
Hi @georghinkel ,

Don't worry, I change the metamodel so that now it uses "AND" as operator for the reference case and Epsilon also.

Sorry, the last time I wasn't paying attention to the weird "and" parsing since all scenarios are passed.
Only today, while playing with more complex OCL expressions, I noticed the parsing errors.
